import { useEffect, useState } from "react";
import { CreditCard, Users } from "lucide-react";
import { toast } from "sonner";
import AppShell from "../components/AppShell";
import { billingAPI } from "../services/api";

export default function AdminAssinaturas() {
  const [dados, setDados] = useState(null);
  useEffect(() => { billingAPI.adminAssinaturas().then(({ data }) => setDados(data)).catch((e) => toast.error(e.response?.data?.error || "Acesso não autorizado")); }, []);
  const data = (v) => v ? new Intl.DateTimeFormat("pt-BR").format(new Date(v)) : "—";
  return <AppShell><main className="mx-auto max-w-[1400px] px-4 py-7 sm:px-6 lg:px-10 lg:py-10"><header className="mb-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-indigo-600">Administração</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Usuários e assinaturas</h1><p className="mt-2 text-slate-500">Acompanhamento comercial da plataforma.</p></header>{!dados ? <div className="app-surface p-16 text-center text-slate-500">Carregando assinaturas...</div> : <><div className="mb-7 grid grid-cols-2 gap-4 lg:grid-cols-4">{[["Total", dados.resumo.total], ["Assinaturas ativas", dados.resumo.ativas], ["Em teste", dados.resumo.testes], ["Inativas", dados.resumo.inativas]].map(([nome, valor], i) => <div key={nome} className="app-surface p-5"><div className={`mb-4 grid h-9 w-9 place-items-center rounded-lg ${i === 1 ? "bg-emerald-100 text-emerald-600" : "bg-indigo-50 text-indigo-600"}`}>{i ? <CreditCard className="h-4 w-4"/> : <Users className="h-4 w-4"/>}</div><p className="text-sm text-slate-500">{nome}</p><p className="mt-1 text-2xl font-bold">{valor}</p></div>)}</div><div className="app-surface overflow-hidden"><div className="overflow-x-auto"><table className="min-w-full"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Cliente</th><th className="px-5 py-4">Plano</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Fim do período</th><th className="px-5 py-4">Cadastro</th></tr></thead><tbody className="divide-y divide-slate-100">{dados.usuarios.map((u) => <tr key={u.id} className="text-sm"><td className="px-5 py-4"><b className="block">{u.nome_negocio || u.nome || "Sem nome"}</b><span className="text-slate-500">{u.email}</span></td><td className="px-5 py-4 capitalize">{u.plano}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${u.assinatura_status === "active" ? "bg-emerald-50 text-emerald-700" : u.assinatura_status === "trialing" ? "bg-indigo-50 text-indigo-700" : "bg-rose-50 text-rose-700"}`}>{u.assinatura_status}</span></td><td className="px-5 py-4 text-slate-600">{data(u.assinatura_periodo_fim || u.trial_ends_at)}</td><td className="px-5 py-4 text-slate-600">{data(u.created_at)}</td></tr>)}</tbody></table></div></div></>}</main></AppShell>;
}
