import { useEffect } from "react";
import { Link } from "react-router-dom";
import { CalendarDays, CheckCircle2, Clock, MessageCircle, ShieldCheck, Users } from "lucide-react";
import { brand } from "../config/brand";
import { trackMarketing } from "../utils/marketing";

const dinheiro = (v) => (v / 100).toFixed(2).replace(".", ",");
const recursos = [
  [CalendarDays, "Agenda organizada", "Visualize compromissos em cards, lista ou calendário e evite conflitos de horário."],
  [Users, "Clientes centralizados", "Mantenha contatos, histórico e observações importantes sempre à mão."],
  [MessageCircle, "Lembretes automáticos", "Reduza faltas com lembretes por e-mail e WhatsApp."],
  [Clock, "Agendamento online", "Compartilhe seu link e deixe o cliente escolher um horário disponível."],
];

export default function Landing() {
  useEffect(() => { document.title = `${brand.name} | Agendamentos simples e profissionais`; trackMarketing("landing_view", "/"); }, []);
  const cta = () => trackMarketing("signup_click", "/");
  return <div className="min-h-screen bg-white text-slate-900"><header className="sticky top-0 z-40 border-b border-slate-200/80 bg-white/90 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6"><Link to="/" className="flex items-center gap-3 font-bold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-indigo-600 text-white"><CalendarDays className="h-5 w-5"/></span>{brand.name}</Link><nav className="hidden items-center gap-7 text-sm font-semibold text-slate-600 md:flex"><a href="#recursos" className="hover:text-indigo-600">Recursos</a><a href="#planos" className="hover:text-indigo-600">Planos</a><a href="#duvidas" className="hover:text-indigo-600">Dúvidas</a></nav><div className="flex items-center gap-2"><Link to="/login" onClick={() => trackMarketing("login_click", "/")} className="btn-secondary border-0 px-3 py-2 sm:px-4">Entrar</Link><Link to="/register" onClick={cta} className="btn-primary px-3 py-2 sm:px-4">Teste grátis</Link></div></div></header>
    <main><section className="relative overflow-hidden bg-slate-950"><div className="absolute inset-0 bg-[radial-gradient(circle_at_18%_20%,rgba(99,102,241,.34),transparent_32%),radial-gradient(circle_at_82%_70%,rgba(14,165,233,.18),transparent_30%)]"/><div className="relative mx-auto grid max-w-7xl gap-14 px-4 py-20 sm:px-6 lg:grid-cols-2 lg:items-center lg:py-28"><div><span className="inline-flex items-center gap-2 rounded-full border border-indigo-400/20 bg-indigo-400/10 px-3 py-1.5 text-xs font-bold text-indigo-300"><CheckCircle2 className="h-4 w-4"/>14 dias grátis · sem cartão</span><h1 className="mt-7 text-4xl font-bold leading-tight tracking-tight text-white sm:text-6xl">Sua agenda cheia.<br/><span className="text-indigo-400">Sua rotina leve.</span></h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-slate-300">Agendamentos, clientes, serviços e lembretes em uma plataforma simples para profissionais que querem crescer.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link to="/register" onClick={cta} className="btn-primary px-7 py-3.5">Começar teste grátis</Link><a href="#recursos" className="inline-flex items-center justify-center rounded-xl border border-white/15 px-7 py-3.5 text-sm font-semibold text-white hover:bg-white/5">Conhecer recursos</a></div><p className="mt-4 text-xs text-slate-500">Cancele quando quiser. Seus dados continuam seus.</p></div><div className="rounded-3xl border border-white/10 bg-white/5 p-4 shadow-2xl backdrop-blur"><div className="rounded-2xl bg-[#f6f7fb] p-5"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Hoje</p><p className="mt-1 text-xl font-bold">Próximos atendimentos</p></div><span className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-bold text-white">+ Novo</span></div>{[["09:00","Mariana Alves","Consulta","Confirmado"],["10:30","Carlos Lima","Avaliação","Pendente"],["14:00","Ana Souza","Retorno","Confirmado"]].map(([h,n,s,st]) => <div key={h} className="mb-3 flex items-center gap-4 rounded-xl border border-slate-200 bg-white p-4"><span className="font-bold text-indigo-600">{h}</span><span className="min-w-0 flex-1"><b className="block truncate">{n}</b><small className="text-slate-500">{s}</small></span><small className={`rounded-full px-2 py-1 font-semibold ${st === "Confirmado" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{st}</small></div>)}</div></div></div></section>
      <section id="recursos" className="mx-auto max-w-7xl px-4 py-20 sm:px-6"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-indigo-600">Tudo em um só lugar</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Menos tarefas manuais. Mais atendimento.</h2><p className="mt-4 text-slate-500">Recursos pensados para uma operação profissional desde o primeiro cliente.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{recursos.map(([Icon,t,d]) => <article key={t} className="rounded-2xl border border-slate-200 p-6 transition hover:-translate-y-1 hover:shadow-lg"><span className="grid h-11 w-11 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><Icon className="h-5 w-5"/></span><h3 className="mt-5 text-lg font-bold">{t}</h3><p className="mt-2 text-sm leading-relaxed text-slate-500">{d}</p></article>)}</div></section>
      <section id="planos" className="bg-[#f6f7fb] py-20" onMouseEnter={() => trackMarketing("pricing_view", "/")}><div className="mx-auto max-w-5xl px-4 sm:px-6"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-indigo-600">Planos transparentes</p><h2 className="mt-3 text-3xl font-bold">Comece grátis. Evolua quando precisar.</h2></div><div className="mt-12 grid gap-6 lg:grid-cols-2"><Plano nome="Básico" valor={brand.basicPrice} recursos={["Agenda e clientes", "Até 5 serviços", "Lembretes por e-mail"]}/><Plano nome="Profissional" valor={brand.professionalPrice} destaque recursos={["Serviços ilimitados", "Agenda pública", "WhatsApp e recursos avançados"]}/></div></div></section>
      <section id="duvidas" className="mx-auto max-w-3xl px-4 py-20 sm:px-6"><div className="text-center"><h2 className="text-3xl font-bold">Perguntas frequentes</h2></div><div className="mt-10 divide-y divide-slate-200 border-y border-slate-200">{[["Preciso informar cartão no teste?","Não. Você pode testar os recursos por 14 dias antes de contratar."],["Posso cancelar quando quiser?","Sim. A assinatura pode ser gerenciada e cancelada pelo Portal do Cliente."],["Meus clientes precisam criar conta?","Não. Eles podem usar seu link público para agendar sem login."],["Funciona no celular?","Sim. O painel e a página pública são responsivos."]].map(([q,a]) => <details key={q} className="group py-5"><summary className="cursor-pointer list-none font-bold">{q}<span className="float-right text-indigo-600 group-open:rotate-45">+</span></summary><p className="mt-3 text-sm leading-relaxed text-slate-500">{a}</p></details>)}</div></section>
      <section className="bg-indigo-600"><div className="mx-auto max-w-4xl px-4 py-16 text-center text-white"><h2 className="text-3xl font-bold">Pronto para organizar sua agenda?</h2><p className="mt-3 text-indigo-100">Comece agora e configure seu negócio em poucos minutos.</p><Link to="/register" onClick={cta} className="mt-7 inline-flex rounded-xl bg-white px-7 py-3 font-bold text-indigo-700 hover:bg-indigo-50">Começar teste grátis</Link></div></section></main>
    <footer className="bg-slate-950 text-slate-400"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-4 py-8 text-sm sm:px-6 md:flex-row md:items-center md:justify-between"><span>© 2026 {brand.name}. Todos os direitos reservados.</span><div className="flex gap-5"><Link to="/termos" className="hover:text-white">Termos de Uso</Link><Link to="/privacidade" className="hover:text-white">Privacidade</Link><a href={`mailto:${brand.supportEmail}`} className="hover:text-white">Suporte</a></div></div></footer></div>;
}

function Plano({ nome, valor, recursos, destaque=false }) { return <article className={`relative rounded-2xl border bg-white p-7 ${destaque ? "border-indigo-500 ring-4 ring-indigo-500/10" : "border-slate-200"}`}>{destaque && <span className="absolute right-5 top-5 rounded-full bg-indigo-100 px-3 py-1 text-xs font-bold text-indigo-700">RECOMENDADO</span>}<h3 className="text-2xl font-bold">{nome}</h3><p className="mt-4"><b className="text-4xl">R$ {dinheiro(valor)}</b><span className="text-slate-500">/mês</span></p><ul className="mt-7 space-y-3">{recursos.map(r => <li key={r} className="flex gap-3 text-sm text-slate-600"><CheckCircle2 className="h-5 w-5 text-emerald-500"/>{r}</li>)}</ul><Link to="/register" onClick={() => trackMarketing("signup_click", "/")} className={`${destaque ? "btn-primary" : "btn-secondary"} mt-8 w-full`}>Testar gratuitamente</Link></article>; }
